### ISSUE TITLE
actor runtime has not been configured

### ISSUE THREAD

**Issue by trey-rosius** [diagridio/catalyst-feedback#17]
**Describe the bug**
Dapr Workflow immediately terminates with the error below, when started 

```
  raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
== APP - payment-service == grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
== APP - payment-service ==     status = StatusCode.UNKNOWN
== APP - payment-service ==     details = "actor runtime has not been configured"
== APP - payment-service ==     debug_error_string = "UNKNOWN:Error received from peer ipv4:13.57.153.235:443 {created_time:"2024-07-16T16:15:14.044779-07:00", grpc_status:2, grpc_message:"actor runtime has not been configured"}"

```

**To Reproduce**
Git clone this repo(https://github.com/trey-rosius/package-delivery-microservice) and run the `diagrid dev start` command.

From Postman or any API Testing application, send a post request to this endpoint (http://localhost:5006/v1.0/payment)
With body 

```
{
    "amount":500,
    "user_id":"USER_ID",
    "package_id":"PAYMENT_ID"
}

```

**Expected behavior**

The workflow is supposed to start running and timeout in 300 seconds if 
a) An `approve_payment` event wasn't raised 

OR

b) A `cancel_payment` event wasn't raised.

**Screenshots**
![Screenshot](https://github.com/user-attachments/assets/b55165a1-12fe-4dfd-b523-6124de538f0d)

**Additional context**
```
(.venv) ➜  package-delivery-microservice git:(master) diagrid version
version: 0.137.0
git commit: 8bf07bda5ab42f02d394867d2a25a45bfe8f7afb
git version: v0.2.0-1361-g8bf07bd
date: 2024-07-10
```

**Comment by kendallroden** [comment]
We've tested it in your project directly and no longer can reproduce this issue. It should be resolved.
