### ISSUE TITLE
Bug Report: InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails

### ISSUE THREAD

**Issue by trey-rosius** [diagridio/catalyst-feedback#19]
**Describe the bug**
When I save to state and publish an event, I get this error infrequently. Sometimes it happens, other times, the code works as intended. 
I'm not using the OUTBOX pattern

`{
    "detail": "<_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"upstream connect error or disconnect/reset before headers. reset reason: connection termination\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"upstream connect error or disconnect/reset before headers. reset reason: connection termination\", grpc_status:14, created_time:\"2024-08-27T10:00:15.692326+01:00\"}\"\n>"
}`

**To Reproduce**
Here's the repo 
https://github.com/trey-rosius/group-chat-microservice/tree/main
Run the application and make this post request.

`/v1.0/state/groups/{group_id}/participants'`

You'll have to setup a pub-sub  AWS broker and a state.

**Expected behavior**
I expected the item to save and then publish the event successfully without throwing any errors.

**Screenshots**
![Screenshot 2024-08-27 at 11 50 33](https://github.com/user-attachments/assets/fda8d600-d042-4ce4-94b6-56aaa87e8990)

**Additional context**

**Comment by kendallroden** [comment]
details: 
- Using the python SDK 
- Occurs when using the dev tunnel (transient- happens sometimes and not other times) 
- Not using outbox 
- HTTP request looks like its going to catalyst sidecar in the above but its just his http endpoint schema that he modeled after the dapr one

**Comment by jjcollinge** [comment]
We believe we have a root cause in the upstream Dapr AWS SNS/SQS implementation, we'll be patching internally and contributing a fix upstream ASAP.

**Comment by jjcollinge** [comment]
Upstream PR https://github.com/dapr/components-contrib/pull/3513
