### ISSUE TITLE
Bug Report: Socket closed, when running workflow

### ISSUE THREAD

**Issue by trey-rosius** [diagridio/catalyst-feedback#20]
**Describe the bug**

Workflow times out and never fully runs.

`== APP - loan-broker ==     raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
== APP - loan-broker == grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
== APP - loan-broker ==         status = StatusCode.UNAVAILABLE
== APP - loan-broker ==         details = "Socket closed"
== APP - loan-broker ==         debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-08-27T12:01:05.756489+01:00", grpc_status:14, grpc_message:"Socket closed"}"
== APP - loan-broker == >
== APP - loan-broker == 
== APP - loan-broker == During handling of the above exception, another exception occurred:
== APP - loan-broker == 
`

**To Reproduce**
Here's the Complete Code 
https://github.com/trey-rosius/loan_broker_application

Run the code and start a workflow with this endpoint `http://localhost:5006/v1.0/seek-loan`
**Expected behavior**
I expected the workflow to run and execute it's individual activities.

**Screenshots**
![Screenshot 2024-08-27 at 12 05 45](https://github.com/user-attachments/assets/9ee70a9f-89a0-4cd0-915a-a732c75e2bb7)

**Additional context**

**Comment by famarting** [comment]
Hi, we have been investigating the issue and although we haven't reproduced this exact error we already found various errors that could led to this bug

We will apply our bug fixes as soon as possible.

Btw I connected to your project, connected the app and created a workflow which is now in failed state.

And sorry for the inconvenience!

**Comment by famarting** [comment]
I think I have identified the root cause of the bug. We currently have a bug that makes us not being able to support workflows executing activities concurrently. i.e https://github.com/trey-rosius/loan_broker_application/blob/main/loan-broker/workflow.py#L40 . We are actively working on getting a bugfix.

One option that could unblock you could be to rewrite that workflow so it executes the different activities in sequence instead of using the `yield when_all` statement

**Comment by trey-rosius** [comment]
> I think I have identified the root cause of the bug. We currently have a bug that makes us not being able to support workflows executing activities concurrently. i.e https://github.com/trey-rosius/loan_broker_application/blob/main/loan-broker/workflow.py#L40 . We are actively working on getting a bugfix.
> 
> One option that could unblock you could be to rewrite that workflow so it executes the different activities in sequence instead of using the `yield when_all` statement

Thanks for the feedback. However, the main objective of this workflow was to execute the tasks in parallel and then aggregate the results.  The Fan In / Fan Out Pattern. 
I have a another workflow that executes tasks sequentially. I'll test it out and see if it works

**Comment by famarting** [comment]
@trey-rosius hey! yesterday we deployed the fixes to prod, would you be able to double check if the issue is fixed for you? Thank you

**Comment by trey-rosius** [comment]
@famarting It works like a charm.

Thanks. 
I'll close this issue now
