### ISSUE TITLE
Bug Report: Catalyst UI Bug.Can't find any subscriptions, even if you create some.

### ISSUE THREAD

**Issue by trey-rosius** [diagridio/catalyst-feedback#21]
**Describe the bug**
On the Catalyst UI, all pub/sub subscriptions are gone. Creating new ones make no difference. 

**To Reproduce**
Try creating a pub/sub subscription through the catalyst UI.

**Expected behavior**
I expected to see a list of created pub/sub subscriptions

**Screenshots**
![Screenshot 2024-08-31 at 11 57 42](https://github.com/user-attachments/assets/b93df7c2-223b-409d-bebb-2d8d1d932ab3)

**Additional context**

**Comment by kendallroden** [comment]
Hey Rosius, can you see them in the CLI and still use them? Will get the team on it

**Comment by trey-rosius** [comment]
Yes I can Kendall. I used the manifest to update the subscription through the CLI.

**Comment by trey-rosius** [comment]
> Hey Rosius, can you see them in the CLI and still use them? Will get the team on it

Yes I can Kendall . I used the manifest to update the subscription through the CLI.

**Comment by ConstantinChirila** [comment]
Hey both! This was fixed, and should reach production by Tuesday!
Thank you!

**Comment by trey-rosius** [comment]
fixed
