### ISSUE TITLE
Bug Report: state store <TABLE_NAME> is not found

### ISSUE THREAD

**Issue by trey-rosius** [diagridio/catalyst-feedback#22]
**Describe the bug**

This issue is intermittent. The table in the error message exist and data has been saved to it a couple of times. Sometimes data saves, other times, `state store ....... is not found.`

```{
    "detail": "<_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.INVALID_ARGUMENT\n\tdetails = \"state store typing-indicator-table is not found\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer ipv4:52.52.121.154:443 {created_time:\"2024-09-01T12:08:45.833533+01:00\", grpc_status:3, grpc_message:\"state store typing-indicator-table is not found\"}\"\n>"
}
```

Diagrid Version

```
version: 0.155.0
git commit: 6e43ca52ba8f5bac977819366af98a37c685a070
git version: v0.2.0-1378-g6e43ca5
date: 2024-08-28
```
```
Programming Language :Python
```

**To Reproduce**
Here's the complete code https://github.com/trey-rosius/group-chat-microservice

When running locally, make a post request to this endpoint 
` http://localhost:5003/typing`

Here's the request body 

```{
    "id":"11fe0855-e065-4103-8a5b-f9933e41271d",
    "user_id":"a5c93f2d-9602-4f91-9c8b-3aeffd1314f0",
     "typing":true,
    "group_id":"7eb12e0b-06f2-49b4-89c3-6a0e36c0d21d"
}
```

**Expected behavior**
Expected the data to be saved properly to the state.

**Screenshots**
![Screenshot 2024-09-01 at 12 13 34](https://github.com/user-attachments/assets/900d7fa9-6b56-44fd-b001-32138ad17500)
![Screenshot 2024-09-01 at 12 16 19](https://github.com/user-attachments/assets/01c3f0d3-12bf-49ea-a546-722b48d75fe7)
![Screenshot 2024-09-01 at 12 31 51](https://github.com/user-attachments/assets/0f4064d0-521a-4e22-b1a8-b5b1fcf5fc24)

**Additional context**

**Comment by trey-rosius** [comment]
So if i go to the catalyst UI, `edit state` and click save. Give it a couple minutes, the error goes away.

![Screenshot 2024-09-01 at 12 38 04](https://github.com/user-attachments/assets/1dec6144-1b2f-4bea-af8c-9dc5cf3fee4b)
![Screenshot 2024-09-01 at 12 43 41](https://github.com/user-attachments/assets/78ed9e01-a2f4-470d-8100-5c794072bb18)

And this happens for all the created states.

**Comment by jjcollinge** [comment]
Thanks for reporting this! When you were receiving the error intermittently - how long was it behaving like this for? Was it stuck like this until you did the edit/save or did it resolve itself after some time without any further input?

**Comment by trey-rosius** [comment]
> Thanks for reporting this! When you were receiving the error intermittently - how long was it behaving like this for? Was it stuck like this until you did the edit/save or did it resolve itself after some time without any further input?

It was stuck. I had to do the edit and save to resolve it. 
Also, I faced this same issue in a previous project. I did the `edit and save` thing to resolve it. However I didn't report the issue because I had left the project stale for about a month before returning to it.

**Comment by jjcollinge** [comment]
Ok thanks @trey-rosius. I'll try to find time to debug this later today. Sorry for the inconvenience.

**Comment by trey-rosius** [comment]
> Ok thanks @trey-rosius. I'll try to find time to debug this later today. Sorry for the inconvenience.

No Worries man. I appreciate it. Let me know if there's anything I can do to assist!

**Comment by jjcollinge** [comment]
@trey-rosius are you able to leave your project in it's current state to help us debug this issue?

**Comment by trey-rosius** [comment]
> @trey-rosius are you able to leave your project in it's current state to help us debug this issue?

sure. No problem @jjcollinge

**Comment by kendallroden** [comment]
issue address and shipping tomorrow
