### ISSUE TITLE
Bug Report: Some Catalyst Components are Down(`ERROR`) Status 

### ISSUE THREAD

**Issue by trey-rosius** [diagridio/catalyst-feedback#24]
**Describe the bug**
Some Catalyst Components are down. 

Please see the attached screenshot

**To Reproduce**
Logging to the Catalyst UI and checkout a project with components.

**Screenshots**
![Screenshot 2024-09-11 at 09 06 33](https://github.com/user-attachments/assets/ffe233c3-f4cb-4e0d-aabf-20c8e7ea804c)
![Screenshot 2024-09-11 at 09 06 54](https://github.com/user-attachments/assets/2518eb05-49a2-480a-85a0-8a7bebd7e6e3)
![Screenshot 2024-09-11 at 10 04 43](https://github.com/user-attachments/assets/d41834c9-659e-4a52-974f-062f165bcc62)

**Additional context**

**Comment by jjcollinge** [comment]
hey @trey-rosius yes this is the same issue as yesterday - it's a memory leak in the Dapr MongoDb component. Yesterday we only mitigated it (which we'll do again now ) but we're not rolling out the actual fix. Should be fixed properly soon.

**Comment by jjcollinge** [comment]
This should have been mitigated. Fix rolling out shortly 👍

**Comment by trey-rosius** [comment]
Nice, Thanks
